### PR TITLE
Add three schema keywords: additionalItems, additionalProperties, patternProperties

### PR DESCRIPTION
**Pull request by davek2**
This branch extends GenSON to support two schema constraints in addition to the current "requires" constraint, and a "merge properties" generation option analogous to the current "merge arrays" option.

Three of the four current keywords define datatypes: type, items, and properties.  The fourth keyword "requires" is a constraint indicating that an object that does not contain all properties listed in "requires" is invalid.
- The keyword "additionalProperties": False is the inverse of "required" - it indicates that an object containing properties not defined in the schema is invalid.
- The keyword "additionalItems": False is the equivalent constraint for arrays - it indicates that a tuple (unmerged) arrary containing items not defined in the schema is invalid.
- The keyword "patternProperties" supports merging of property schemas as the "merge_arrays": True option supports merging of item schemas.  But since properties are named, patternProperties enables a subset of properties to be merged while leaving other properties unmerged.  An object with properties {"a", "b", "c", "1", "2", "3"} could generate a schema with the first three properties left separate and the last three properties merged into a single pattern property matching the regular expression "\d+".

The additionalItems and additionalProperties keywords are required to allow GenSON to support the functionality of jsonschema.net, which has "allow additional items" and "allow additional properties" options.   The patternProperties keyword extends beyond jsonschema.net, which supports merging of item schemas but not merging of property schemas.  Both types of merges are needed.

### CODE REVIEW

**Comment by FrancoisGallard** [comment]
Hello,
This is a useful patch, it fixes an issue I ham having :

schema = {
    "properties": {
        "x": {
            "type": "array",
            "items": {
                "type": "number",
            }
        }
    },
    "required": ["x"],
    "type": "object"
}


scg = Schema()
scg.add_schema(schema)

 genson/generator.py, line 59, in add_schema
    for prop, val in schema.items():
AttributeError: 'str' object has no attribute 'items'

Thanks

François

**Comment by wolverdude** [comment]
@FrancoisGallard: Noted. This sounds like a validation of Issue #14. I'll try to fix it and release a patch. This PR is in the works for the next version.

**Comment by cidrblock** [comment]
This would be a big help. Can we get it added?

**Comment by wolverdude** [comment]
Yeah... I've let this one languish way too long. I'll try to get to it this weekend. If not, then over the new year.

**Comment by wolverdude** [comment]
So, after reviewing things and refreshing myself on what's up with this PR, I've come to the conclusion that it should not be merged. The concept is helpful, and I _will_ implement `patternProperties` at the least, but this PR doesn't really fix the problem. This isn't @davek2's fault. It's the fault of the project's current architecture.

The solution I'm working on will move away from inflexible root schema `__init__` arguments in favor of using "seed schemas" which will tell the library how to handle incoming objects in cases where there are multiple valid ways of doing so. `patternProperties` fits very nicely into this paradigm. `additionalProperties` could also be implemented fairly easily, and `additionalItems` should work already.

This is a larger refactor that addresses several other issues as well. Unfortunately, I wasn't able to finish this weekend, but I'll keep working on it and try to get it out by the end of the year.

**Comment by cidrblock** [comment]
Thanks @wolverdude.  I've integrated json schema and genson into a project I've been working on.  Consider it a UI for the two:  https://github.com/cidrblock/td4a#modes.  thx again for your efforts.

**Comment by wolverdude** [comment]
Thanks for posting your module; it always helps to see how this code is being used. May I ask how, specifically you plan to use `patternProperties`?

**Pull request closed without merging**
